import { doc, getDoc } from 'firebase/firestore';
import Head from 'next/head';
import router from 'next/router';
import { useContext, useEffect } from 'react';
import { firebaseDb } from '../../../src/firebase/firebase';
import { AuthContext } from '../../../src/providers/auth/AuthProvider';
import styles from '../../../styles/Home.module.css';

export default function AddRoomPage({ id }: { id: string }) {
  const { state } = useContext(AuthContext);

  useEffect(() => {
    if (!state.isUserLoggedIn) {
      console.log('You are not logged in!');
      router.push('/');
      return;
    }

    async function fetchHotel() {
      const hotelRef = doc(firebaseDb, 'hotels', id);
      const hotelSnapshot = await getDoc(hotelRef);

      if (hotelSnapshot.exists()) {
        // const hotelData = hotelSnapshot.data();
        // setHotelName(hotelData?.name);
        // setHotelLocation(hotelData?.location);
        // setHotelDescription(hotelData?.description);
        // setHotelOwnerId(hotelData?.ownerId);
      } else {
        console.log('Hotel not found!');
        router.push('/');
      }
    }

    fetchHotel();
  }, [id, state]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Unde Dorm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Room {id}</h1>
      </main>
    </div>
  );
}

export async function getServerSideProps(context: any) {
  const { id } = context.query;
  return {
    props: {
      id: id,
    },
  };
}