import Head from 'next/head';
import styles from '../styles/Hotels.module.css';
import { useContext, useEffect, useState } from 'react';
import { AuthContext } from '../src/providers/auth/AuthProvider';
import { useRouter } from 'next/router';
import { firebaseDb, storage, storageRef } from '../src/firebase/firebase';
import { collection, getDocs } from 'firebase/firestore';

export default function HotelList() {
  const { state } = useContext(AuthContext);
  const router = useRouter();
  const hotelsRef = collection(firebaseDb, 'hotels');

  const [hotelImages, setHotelImages] = useState<string[]>([]);
  const [hotelNames, setHotelNames] = useState<string[]>([]);
  const [hotelLocations, setHotelLocations] = useState<string[]>([]);
  const [hotelDescriptions, setHotelDescriptions] = useState<string[]>([]);

  useEffect(() => {
    if (!state.isUserLoggedIn && !state.isUserLoaded) {
      console.log('You are not logged in!');
      router.push('/');
    } else {
      console.log(hotelsRef);
      const getHotels = async () => {
        const hotelsSnapshot = await getDocs(hotelsRef);
        const hotelsData = hotelsSnapshot.docs
          .map((doc) => doc.data())
          .filter((data) => data.Name !== undefined && data.Name !== null);

        const hotelImages = hotelsData.map((data) => data.Images);
        const hotelNames = hotelsData.map((data) => data.Name);
        const hotelLocations = hotelsData.map((data) => data.Location);
        const hotelDescriptions = hotelsData.map((data) => data.Description);

        // Set the state with the hotel names and locations
        setHotelImages(hotelImages);
        setHotelNames(hotelNames);
        setHotelLocations(hotelLocations);
        setHotelDescriptions(hotelDescriptions);
      };
      getHotels();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Unde Dorm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Cautare de hoteluri</h1>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th>Location</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            {hotelNames.map((name, index) => (
              <tr key={name}>
                <td>{hotelImages[index].at(0)}</td>
                <td className={styles.td}>{name}</td>
                <td className={styles.td}>{hotelLocations[index]}</td>
                <td className={styles.td}>{hotelDescriptions[index]}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
}
