import Head from 'next/head';
import { provider, auth } from '../firebase';
import styles from '../styles/Home.module.css';
import {
  getAuth,
  signInWithPopup,
  GoogleAuthProvider,
  onAuthStateChanged,
} from 'firebase/auth';
import { useState } from 'react';

export default function Home() {
  const [isUserLoaded, setIsUserLoaded] = useState(false);
  const [username, setUsername] = useState('Guest');

  const signInWithGoogle = () => {
    signInWithPopup(auth, provider)
      .then((result) => {
        // This gives you a Google Access Token. You can use it to access the Google API.
        const credential = GoogleAuthProvider.credentialFromResult(result);
        const token = credential?.accessToken;
        // The signed-in user info.
        const user = result.user;
        console.log(result);
        // setUsername(result.user.displayName ?? 'nume');
        // IdP data available using getAdditionalUserInfo(result)
        // ...
      })
      .catch((error) => {
        setUsername('Eroare');
        console.warn('TEST', error);
      });
  };

  const signOut = () => {
    auth.signOut().then(() => {
      setUsername('Guest');
    });
  };

  onAuthStateChanged(auth, (user) => {
    setIsUserLoaded(false);
    if (user) {
      // User is signed in, see docs for a list of available properties
      // https://firebase.google.com/docs/reference/js/firebase.User
      setUsername(user.displayName ?? 'nume');
      // setIsUserLoaded(true);
      // ...
    } else {
      // User is signed out
      // ...
      // setUsername('Guest');
    }
    setIsUserLoaded(true);
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Unde Dorm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isUserLoaded ? (
          <h1 className={styles.title}>
            Hello, {username}! Welcome to <a href="">UndeDorm</a>
          </h1>
        ) : (
          <h1 className={styles.title}>Loading</h1>
        )}

        <div className={styles.grid}>
          <a href="/profile" className={styles.card}>
            <h2>Profil &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="/reservations" className={styles.card}>
            <h2>Rezervari &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="/hotels" className={styles.card}>
            <h2>Cauta hotel &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>

          <button onClick={signInWithGoogle} className={styles.card}>
            <p>Log in with Google</p>
          </button>
          <button onClick={signOut} className={styles.card}>
            <p>Log out</p>
          </button>
        </div>
      </main>
    </div>
  );
}
