import Head from 'next/head';
import { provider, auth } from '../src/firebase/firebase';
import styles from '../styles/Home.module.css';
import { signInWithPopup, signInWithEmailAndPassword } from 'firebase/auth';
import { useState } from 'react';
import router from 'next/router';

export default function SignInPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const signInWithGoogle = () => {
    signInWithPopup(auth, provider)
      .then((result) => {
        router.push('/');
      })
      .catch((error) => {
        console.warn('[SignIn]', error);
      });
  };

  const signInWithCredentials = () => {
    signInWithEmailAndPassword(auth, email, password)
      .then(() => {
        router.push('/');
      })
      .catch((error) => {
        console.warn('[SignIn]', error);
        if (error.code === 'auth/user-not-found') {
          alert('Account not found!');
        } else if (error.code === 'auth/wrong-password') {
          alert('Incorrect password!');
        }
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Unde Dorm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Log in</h1>
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          className={styles.input}
        />
        <input
          type="password"
          placeholder="Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          className={styles.input}
        />
        <button onClick={signInWithCredentials} className={styles.card}>
          <p>Log in</p>
        </button>

        <button onClick={signInWithGoogle} className={styles.card}>
          <p>Log in with Google</p>
        </button>
      </main>
    </div>
  );
}
