import Head from 'next/head';
import { provider, auth } from '../src/firebase/firebase';
import styles from '../styles/Home.module.css';
import { signInWithPopup, signInWithEmailAndPassword } from 'firebase/auth';
import { useContext, useEffect, useState } from 'react';
import router from 'next/router';
import { AuthContext } from '../src/providers/auth/AuthProvider';

export default function SignInPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const { state, dispatch } = useContext(AuthContext);

  if (state.isUserLoggedIn) {
    console.log('You are currently logged in!');
    router.push('/');
    return;
  }

  const signInWithGoogle = () => {
    signInWithPopup(auth, provider)
      .then(() => {
        dispatch({
          type: 'sign-in',
          payload: {
            uuid: auth.currentUser?.uid,
          },
        });
        router.push('/');
      })
      .catch((error) => {
        console.warn('[SignIn]', error);
      });
  };

  const signInWithCredentials = () => {
    signInWithEmailAndPassword(auth, email, password)
      .then(() => {
        dispatch({
          type: 'sign-in',
          payload: {
            uuid: auth.currentUser?.uid,
          },
        });
        router.push('/');
      })
      .catch((error) => {
        console.warn('[SignIn]', error);
        if (error.code === 'auth/user-not-found') {
          alert('Account not found!');
        } else if (error.code === 'auth/wrong-password') {
          alert('Incorrect password!');
        }
      });
  };

  const forgotPassword = () => {
    router.push('/forgotPassword');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Unde Dorm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Log in</h1>
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          className={styles.input}
        />
        <input
          type="password"
          placeholder="Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          className={styles.input}
        />
        <button onClick={signInWithCredentials} className={styles.card}>
          <p>Log in</p>
        </button>

        <button onClick={signInWithGoogle} className={styles.card}>
          <p>Log in with Google</p>
        </button>

        <button onClick={forgotPassword} className={styles.card}>
          <p>Forgot Password</p>
        </button>
      </main>
    </div>
  );
}
